// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFBrFGUyH8ficJj_gqPXDGV2WsRrSY3ns',
    appId: '1:52459158115:web:30e378e30557632aa91656',
    messagingSenderId: '52459158115',
    projectId: 'the-wall-flutter',
    authDomain: 'the-wall-flutter.firebaseapp.com',
    storageBucket: 'the-wall-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfN1gi7PyRfhfSoUmqYu5ijFwoJYZFNXw',
    appId: '1:52459158115:android:32a4fb6b486d31eea91656',
    messagingSenderId: '52459158115',
    projectId: 'the-wall-flutter',
    storageBucket: 'the-wall-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxAVNdXGcL3kRi-kAKI6EWI5W_uqAw5A',
    appId: '1:52459158115:ios:9c481d34f0ddf922a91656',
    messagingSenderId: '52459158115',
    projectId: 'the-wall-flutter',
    storageBucket: 'the-wall-flutter.appspot.com',
    iosClientId: '52459158115-7uf4m771ur1n7tqqli24l3ae5kn5odm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxAVNdXGcL3kRi-kAKI6EWI5W_uqAw5A',
    appId: '1:52459158115:ios:f27ca149e750cf3ea91656',
    messagingSenderId: '52459158115',
    projectId: 'the-wall-flutter',
    storageBucket: 'the-wall-flutter.appspot.com',
    iosClientId: '52459158115-08r7rj6ug9tiieme9eo82m4urs71hdlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWall.RunnerTests',
  );
}
